### ISSUE TITLE
Permissions view creates empty files in home folder

### ISSUE THREAD

**Issue by cassidyjames** [elementary/switchboard-plug-applications#121]
A 0-byte file named each Flatpak ID is created when opening the Applications settings. :scream: 

![Screenshot from 2020-09-18 12 01 56](https://user-images.githubusercontent.com/611168/93630181-c8fafa00-f9a6-11ea-88c4-5a136c9129ed.png)

You can delete them, but the next time you open the plug, they're recreated.

**Comment by danrabbit** [comment]
My guess is there's something where we're not waiting for flatpak to return the correct folder maybe. Haven't investigated much, but I can confirm
