### ISSUE TITLE
Loading plug takes too long

### ISSUE THREAD

**Issue by hanaral** [elementary/switchboard-plug-applications#130]
On all my machines there is a good few second pause when opening it, I often think that I mis-clicked only to realise it hasn't loaded yet. I presume it's caused by the flatpak permissions being checked, but there must be a way to load them seperately from the plug i.e the permissions page is greyed out until it is loaded in the background

**Comment by danrabbit** [comment]
I believe this should be resolved by https://github.com/elementary/switchboard-plug-applications/pull/124

Are you running from the latest git?

**Comment by cassidyjames** [comment]
Ah yeah that does seem to resolve it for me here. I'd marked as confirmed because I noticed this the other day and didn't know it was already fixed in the meantime. :smile:

**Comment by hanaral** [comment]
> I believe this should be resolved by #124
> 
> Are you running from the latest git?

Oop you're right
