### ISSUE TITLE
Missing descriptions of custom commands in Startup tab.

### ISSUE THREAD

**Issue by xchan14** [elementary/switchboard-plug-applications#141]
## What Happened
The added custom startup command shows empty.
![Screenshot from 2020-11-10 00-58-23](https://user-images.githubusercontent.com/26490513/98572732-ed14f080-22f0-11eb-868b-ff3e2f52bbbc.png)

## Expected Behavior
The command text should be shown.

## Platform Information
elementary OS 5.1.7 Hera

**Comment by jeremypw** [comment]
Not reproducible on Odin
