### ISSUE TITLE
Blocking home folder access doesn't effect flatpaked apps with hardcoded dir.'s

### ISSUE THREAD

**Issue by hanaral** [elementary/switchboard-plug-applications#153]
## What Happened

Seems that flatpak apps like Zoom which have specific directory access don't get effected by toggling off home or all folder access (in Zoom's case, I disabled access to my home folder, but it evidently can continue reading/writing `~/Documents/Zoom` to it's hearts contempt)

## Expected Behavior

Settings should do what they say, and display info on odd configurations like Zoom
See #148 

## Steps to Reproduce

1. Open and close Zoom
2. Delete ~/Documents/Zoom
3. Disable all folder access for Zoom
4. Open zoom again
5. Check `~/Documents/Zoom` 'existence

## Platform Information

elementary OS 6 Daily

**Comment by lenemter** [comment]
Closing in favor of https://github.com/elementary/switchboard-plug-applications/issues/145
