### ISSUE TITLE
Custom directory access gets overwritten when opening Applications plug

### ISSUE THREAD

**Issue by zelikos** [elementary/switchboard-plug-applications#155]
## What Happened

If you give a Flatpak app access to a specific directory (such as the `flatpak override` command, or with Flatseal), opening the Applications plug overwrites this as the Permissions view doesn't currently support granular filesystem permissions.

An example of this in practice is for the Steam Flatpak; granting access to a specific directory, such as a separate/external drive containing your games library, is necessary if you don't want to, or can't, install all of your games in your home directory. The Steam Flatpak also doesn't run if access to the home directory is granted, so that can't be used as a workaround. Local overrides also seem to take priority over system-wide overrides, so having a system-wide override doesn't work as a workaround either, as the Applications plug leaves an empty override file if the app has default permissions.

## Expected Behavior

Resolving #145 would be ideal in the long term.
In the short term, not overwriting access to specific directories (although I'm not sure if the short-term solution is feasible or not).

## Steps to Reproduce

Using Steam as an example for simplicity, but any Flatpak app can be substituted:

1. `flatpak override --user --filesystem=/path/to/directory com.valvesoftware.Steam`
2. `cat ~/.local/share/flatpak/overrides/com.valvesoftware.Steam` to confirm directory access was granted
3. Open System Settings -> Applications
4. Repeat step 2, see custom directory is no longer there

## Platform Information

elementary OS 6 Early Access

**Comment by queeup** [comment]
Confirm. Always resets my overrides.

**Comment by jalcine** [comment]
Okay, I thought I was freaking out here, thanks for confirming this! I wonder if it'd help to have another tab for apps to have 'mounted directories' or 'allowed paths' versus doing the "Home" / "System" all-or-nothing approaches.

**Comment by jhaygood86** [comment]
This will be fixed by #168 -- underlying cause is that the plug didn't play nice with overrides set via other means

**Comment by jalcine** [comment]
Exciting!
