### ISSUE TITLE
Default Apps change randomly

### ISSUE THREAD

**Issue by tudorjnu** [elementary/switchboard-plug-applications#164]
## What Happened
The default applications change randomly from time to time. The current setup of apps is  Vivaldi web browser, Pictures and Evolution. However, I often open a picture and it randomly goes into the web browser to find out that the default app has randomly changed. Sometimes it gets even worse and it tries to open email with Pictures, internet with Pictures. 

## Steps to Reproduce
I am not too sure of a standard steps that would create a similar situation but my guess is more of a clash between the apps.

## Platform Information
* elementary 6 Odin
* Latest Release
* NVIDIA Corporation GP108M [GeForce MX250], Quad-Core Intel® Core™ i7-10510U CPU @ 1.80GHz

**Comment by abodedis** [comment]
I have this issue as well, in which default applications may change randomly, and even when attempts are made to change them back, it will not remember the changes.  

You may be able to work around this by going to Files, right clicking on a file of the file type that opened incorrectly, Open With -> Select Application -> Set as Default.  For me, this worked for Images at least.

**Comment by abodedis** [comment]
I have this issue as well, in which default applications may change randomly, and even when attempts are made to change them back, it will not remember the changes.

You may be able to work around this by going to Files, right clicking on a file of the file type that opened incorrectly, Open With -> Select Other Application -> Set as Default. For me, this worked for Images at least.

**Comment by tudorjnu** [comment]
Thanks, that seemed to have stabilised it a little. I guess that for now I would just chose default apps per extension basis. :)

**Comment by itoshkov** [comment]
> I have this issue as well, in which default applications may change randomly, and even when attempts are made to change them back, it will not remember the changes.

Are you using Vivaldi as well?

**Comment by jeremypw** [comment]
There are only five places in elementary code where the default application for a type is changed: see https://github.com/search?q=org%3Aelementary+set_as_default_for_type&type=code.  Only two places make general changes - the Files app and the Switchboard Applications plug.  Both require user interaction.  So I am not sure what is going on here - especially if the changes are truly random.  If any pattern can be discerned please report as it could give a clue.

**Comment by itoshkov** [comment]
For me the pattern is, that _Email Client_ and _Image Viewer_ are both set either to _Photo Viewer_ or to _Mail_. At the moment I don't use the _Mail_ client, but I do use the _Photo Viewer_. I'm not sure when this happens, but I mostly see it when I try to open a picture from _Files_ and it opens in _Mail_. But right now I checked the default apps and they are both set to _Picture Viewer_.

**Comment by itoshkov** [comment]
Sorry for the spam, but I decided to play a little bit more. First of all, I exited the browser, to reduce the chance it's doing something in the background.

I opened the settings and saw this:
![Screenshot from 2021-09-05 21 42 43](https://user-images.githubusercontent.com/360805/132137992-55403d8a-b4d4-466d-8c70-98618c4779f2.png)

Next, I fixed the email client to be Mail:
![Screenshot from 2021-09-05 21 43 09](https://user-images.githubusercontent.com/360805/132138014-dea9b484-8f9f-4177-b7bd-97c79ced27c1.png)

I closed the Settings program, reopened it and saw this:
![Screenshot from 2021-09-05 21-43-23](https://user-images.githubusercontent.com/360805/132138035-46e6e39d-0610-483d-8298-c930b70526cc.png)

If I now change the image viewer and exit the settings, it will also change the email client.

**Comment by jeremypw** [comment]
I have reproduced this to the extent that changing the "Mail" default app also changes the "Calendar" default app to the same app.  Also the "Web Browser" and "Image Viewer" apps seem to change together.  I could see anything obvious in the plug code that would cause this so I am wondering whether it is an upstream issue to do with using `AppInfo.set_default_for_type ()`

**Comment by jeremypw** [comment]
I think what is happening is that when an app gets set as default as one mime-type, it is getting set as default for *all the mime-types it supports*.  So most web-browsers will support image mime-types (see MimeType key in their `.desktop` file). I'll try and look into it further.

**Comment by jeremypw** [comment]
Looking at the code again, it seems that when the default app is changed, all the mime-types that the original default supported are mapped to the new app.  Not sure when or why this was done :shrug:

**Comment by dennismayr** [comment]
Can confirm; bitmap images were suddenly reassigned from Photo Viewer ("Visor de Imágenes") to Chrome...
![](https://imgur.com/UwkU7GD.png)

... and when reassigning images to Photo Viewer...
![](https://imgur.com/452SSdI.png)

...the default web browser is also reassigned to Photo Viewer.
![](https://imgur.com/yVlA75l.png)

**Comment by AI-ien** [comment]
I just wanted to confirm this bug. For me random circulation of default apps is between Web browser, Email client and Image viewer. Other seems to stay stable. Also, sometimes default apps are selected entirely wrong, like VLC player for Image viewer.
