### ISSUE TITLE
Add the ability to modify permissions of snaps

### ISSUE THREAD

**Issue by peter-kal** [elementary/switchboard-plug-applications#176]
### Problem

Right now as of writing the permissions of apps packaged as snaps are not able to be modified in the settings. The apps are not even featured in the list.

 

### Proposal

I understand that the distro is taking a more flatpak-focused approach and I acknowledge the reasons behind it. But many users like me use official apps packaged that way, or just prefer them over all. I would like as a user to be able to see and control the permissions of those apps out-of-the-box.

*PS: You are doing a great job, keep up*

**Comment by danirabbit** [comment]
Hey thanks for this report. The native package format for elementary OS is Flatpak and it's the only format that we're targeting for features like this. You'll have to use 3rd party tools to manage other packaging formats.

Closing as "Design conflict" since we only support Flatpak
