### ISSUE TITLE
Bug on 7.1: File Roller is called "Paolo Bacchilega" in System Settings.

### ISSUE THREAD

**Issue by cookednick** [elementary/switchboard-plug-applications#237]
### What Happened?

Quite amusing. "Who is this man and why does he need access to my Home Folder?"

![Screenshot from 2024-06-22 00 48 57](https://github.com/elementary/switchboard-plug-applications/assets/9829045/3adbb364-46f1-43c3-83b9-6cbce942f28e)

### Steps to Reproduce

1. Open System Settings
2. Open Applications screen
3. On the left, you will see the File Roller icon next to its creator's name.

### Expected Behavior

I expect it to be called "File Roller".

### OS Version

7.x (Horus)

### Software Version

Latest release (I have run all updates)

**Comment by cookednick** [comment]
While we're at it, there are actually several incorrect titles in this list. "elementary, Inc." is the name of two applications. One apepars to be the calculator. Midori and something else are called "The GNOME Project".

**Comment by ryonakano** [comment]
Paolo Bacchilega seems to be the author of File Roller, thus here some apps show the maintainer instead of the name.

**Comment by danirabbit** [comment]
This was fixed in the development version of application settings. For some reason we were getting application author here rather than application name
