### ISSUE TITLE
Custom shell script is not being displayed in autostart tab

### ISSUE THREAD

**Issue by jlnr** [elementary/switchboard-plug-applications#26]
My existing `xrandr` startup command is only displayed as an icon without description right now:

![missingdescription](https://user-images.githubusercontent.com/70772/41403386-0702ebc8-6fc5-11e8-9ed4-756f789f7221.png)

It works fine, though. I think this has happened a few times before.

**Comment by arshubham** [comment]
@jlnr Can you share the script. It seems to be working alright for me. Also does it happen immediately or after a reboot?

**Comment by jlnr** [comment]
@arshubham It was something along the lines of `xrandr --output DP-1 --scale 1.25x1.25`, not particular long or anything. I've since reinstalled the system and don't have the script anymore. When I get a chance, I will create a new random startup script and see if it happens again.

**Comment by jlnr** [comment]
I don't have my old installation anymore, and I couldn't reproduce it on my new installation. If it ever happens again, I will reopen this with more technical details.
