### ISSUE TITLE
"Launch %s on startup" is not displayed as translated

### ISSUE THREAD

**Issue by ryonakano** [elementary/switchboard-plug-applications#28]
![2018-09-14 13 47 22](https://user-images.githubusercontent.com/26003928/45530468-c5679200-b825-11e8-902c-d68c8e462a24.png)

The tooltip "Launch %s on startup" (maybe in src/Startup/Widgets/AppRow.vala) is not displayed as translated.

On Juno Beta1, with switchboard-plug-applications 0.1.3.1

## Steps to reproduce the behavior

1. Run switchboard on non-English environment, open applications plug and go to startup pane
2. Add some application to startup
3. Hover the switch in the right of added application
4. The tooltip "Launch %s on startup" is displayed but is not as translated

**Comment by tintou** [comment]
Thanks, It should be fixed with commit c5b1cb054a3f95277974d1ca5741268decea1fc9

**Comment by ryonakano** [comment]
Thank you for your quick fix!!
