### ISSUE TITLE
Startup applications reverts to previous settings upon close

### ISSUE THREAD

**Issue by boetk** [elementary/switchboard-plug-applications#36]
I have tried for the last week to get my startup applications to change, but for some reason every time I try to change the settings nothing happens. The next time I open the settings the startup applications is back to the settings before i edited them.
I also tried the gnome-session-properties to see if something was wrong with the Eos settings, but with no avail. The problem might lie with the general gnome session, but I hope you are able to help me.

I do not seem to be able to change the settings and I am out of ideas, and think it is an issue. 

Please ask for any information you should need to bugfix this.

**Comment by peteruithoven** [comment]
Seeing we've not gotten any more information and the issue hasn't received thumbs up I'm going to close this issue.
