### ISSUE TITLE
Permissions: Handle fully sandboxed apps

### ISSUE THREAD

**Issue by danrabbit** [elementary/switchboard-plug-applications#72]
If apps are completely sandboxed, the sidebar description line is empty. We should probably have something here

![Screenshot from 2020-06-04 11 56 52@2x](https://user-images.githubusercontent.com/7277719/83799339-7fd2a480-a65a-11ea-85ce-78c7071848a3.png)

**Comment by lainsce** [comment]
Maybe hide the subtitle and add a security shield icon by the name?

**Comment by hanaral** [comment]
Could it say something along the lines of _"App does not have or require any permissions."_?
